/// Root widget of the La Casa mobile app: wires up [MaterialApp.router]
/// with the design-token theme (lib/theme/), the go_router navigation
/// shell (lib/navigation/), and the localization delegates generated by
/// `flutter gen-l10n` (lib/l10n/, configured by l10n.yaml).
///
/// System-driven theme by default with a manual override, per
/// `AppTheme`'s own contract doc: `themeMode: ThemeMode.system` here: a
/// later agent wiring an actual theme-toggle setting overrides this from
/// app state rather than changing the default.
library;

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'features/language/language.dart';
import 'l10n/generated/app_localizations.dart';
import 'navigation/app_router.dart';
import 'theme/theme.dart';

class App extends ConsumerWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(goRouterProvider);

    // [languageProvider] has no "system"/unset state to model — it is an
    // `AsyncNotifier<AppLanguage>` (not `AppLanguage?`), seeded from storage
    // and falling back to [AppLanguage.en] on first read/failure (see that
    // provider's and `SecureLanguageRepository.load`'s doc comments). So the
    // only "unset" MaterialApp.locale would ever see is the loading instant
    // before that seed resolves, which `.value` below also folds into
    // English — matching the same default `language_sheet.dart`'s own
    // selected-row highlight uses, so there is no flash to a different
    // locale once the read completes.
    final language = ref.watch(languageProvider).value ?? AppLanguage.en;

    return MaterialApp.router(
      title: 'La Casa',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light(),
      darkTheme: AppTheme.dark(),
      themeMode: ThemeMode.system,
      routerConfig: router,
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,
      // `AppLanguage.wire` is already the ISO 639-1 code each ARB file's
      // `@@locale` uses ("en"/"uz"/"ru", see that getter's doc comment), so
      // it maps straight onto `Locale`'s language-code constructor arg with
      // no translation table. Uzbek is Latin-script here: `Locale('uz')`
      // resolves to CLDR's default Uzbek script, which is Latin (the
      // Cyrillic variant would need the explicit `Locale('uz', 'Cyrl')`
      // script-subtag form) — matching `app_uz.arb`, which is written in
      // Latin script, and SCREENS.md §3.20's "Uz" row, which never
      // distinguishes a script.
      //
      // No unsupported-locale fallback logic is needed beyond this: `locale`
      // is never driven by `Platform`/`window.locale` here (there is no
      // "system" language option to resolve — see above), so it can only
      // ever be one of the three values [AppLanguage] enumerates, and all
      // three are in `supportedLocales`. `localeResolutionCallback` is left
      // at MaterialApp's default for that reason; it would only matter if
      // this ever started reading the device locale.
      locale: Locale(language.wire),
    );
  }
}
